RockShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using RockShop.Core.Contracts;
using System.Security.Claims;

namespace RockShop.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService cartService;

        public CartController(ICartService _cartService)
        {
            cartService = _cartService;
        }

        public async Task<IActionResult> AddToCart(int id)
        {
            try
            {
                var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

                await cartService.AddToCart(id, accId);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("All", "Product");
        }

        public async Task<IActionResult> GetCart()
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

            var model = await cartService.GetCart(accId);

            return View("ShoppingCart", model);
        }

        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

            await cartService.RemoveFromCart(id, accId);

            return RedirectToAction(nameof(GetCart));
        }
    }
}

RockShop/Controllers/StaffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RockShop.Core.Constants;
using RockShop.Core.Contracts;
using RockShop.Core.Models.Staff;
using RockShop.Extensions;

namespace RockShop.Controllers
{
    [Authorize]
    public class StaffController : Controller
    {
        private readonly IStaffService staffService;

        public StaffController(IStaffService _staffService)
        {
            staffService = _staffService;
        }

        [HttpGet]
        public async Task<IActionResult> Become()
        {
            if (await staffService.ExistsById(User.Id()))
            {
                TempData[MessageConstants.ErrorMessage] = "Вие вече сте служител";

                return RedirectToAction("Index", "Home");
            }
            var model = new BecomeStaffModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeStaffModel model)
        {
            var userId = User.Id();
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (await staffService.ExistsById(userId))
            {
                TempData[MessageConstants.ErrorMessage] = "You are already a part of our staff";

                return RedirectToAction("Index", "Home");
            }
            if (await staffService.UserWithPhoneNumberExists(model.PhoneNumber))
            {
                TempData[MessageConstants.ErrorMessage] = "Phone number already exists";
            }

            await staffService.Create(userId, model.PhoneNumber);
            return RedirectToAction("All", "Product"); 
        }
    }
}

RockShop/Views/Shared/_GuitarFormPartial.cshtml
@model GuitarModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Neck"></label>
                <input asp-for="Neck" class="form-control" placeholder="Neck...">
                <span asp-validation-for="Neck" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <input asp-for="Body" class="form-control" placeholder="Body...">
                <span asp-validation-for="Body" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adapters"></label>
                <input asp-for="Adapters" class="form-control" placeholder="Adapters...">
                <span asp-validation-for="Adapters" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bridge"></label>
                <input asp-for="Bridge" class="form-control" placeholder="Bridge...">
                <span asp-validation-for="Bridge" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Frets"></label>
                <input asp-for="Frets" class="form-control" placeholder="Frets...">
                <span asp-validation-for="Frets" class="small text-danger"></span>
            </div>
            <div class="form-check-label">
                <label asp-for="InStock"></label>
                <input asp-for="InStock" class="form-check-input" placeholder="InStock...">
                <span asp-validation-for="InStock" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="Two bedrooms..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId"></label>
                <select asp-for="TypeId" class="form-control">
                    @foreach (var type in Model.Types)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="TypeId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

RockShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rock Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RockShop.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <partial name="_UserMessages" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rock Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">Catalog</a>
                        </li>
                        @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="GetCart">Shopping Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Add">Add a product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Become">Join our Staff</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - RockShop 
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RockShop/Views/Shared/_OrderPartial.cshtml
@model OrderViewModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" placeholder="First Name...">
                <span asp-validation-for="FirstName" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName"></label>
                <input asp-for="SecondName" class="form-control" placeholder="Second Name...">
                <span asp-validation-for="SecondName" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" placeholder="Address...">
                <span asp-validation-for="Address" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" placeholder="+359...">
                <span asp-validation-for="PhoneNumber" class="small text-danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

RockShop/Views/Shared/_ProductFormPartial.cshtml
@model ProductModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Neck"></label>
                <input asp-for="Neck" class="form-control" placeholder="Neck...">
                <span asp-validation-for="Neck" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <input asp-for="Body" class="form-control" placeholder="Body...">
                <span asp-validation-for="Body" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adapters"></label>
                <input asp-for="Adapters" class="form-control" placeholder="Adapters...">
                <span asp-validation-for="Adapters" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bridge"></label>
                <input asp-for="Bridge" class="form-control" placeholder="Bridge...">
                <span asp-validation-for="Bridge" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Frets"></label>
                <input asp-for="Frets" class="form-control" placeholder="Frets...">
                <span asp-validation-for="Frets" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tune"></label>
                <input asp-for="Tune" class="form-control" placeholder="Tune...">
                <span asp-validation-for="Tune" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Holes"></label>
                <input asp-for="Holes" class="form-control" placeholder="Holes...">
                <span asp-validation-for="Holes" class="small text-danger"></span>
            </div>
            <div class="form-check-label">
                <label asp-for="InStock"></label>
                <input asp-for="InStock" class="form-check-input" placeholder="InStock...">
                <span asp-validation-for="InStock" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId"></label>
                <select asp-for="TypeId" class="form-control">
                    @foreach (var type in Model.Types)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="TypeId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

RockShop/Views/Shared/_ProductPartial.cshtml
@model ProductServiceModel

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Product Image">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6>
                Price:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <h6>(@(Model.InStock? "In Stock" : "Not In Stock"))</h6>
            <br />
            <a asp-area="" asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id" 
            asp-route-information="@Model.GetInformation()" class="btn btn-success">Details</a>
            @if (this.User.Identity.IsAuthenticated)
            {
                if (this.User.IsInRole(AdminRoleName))
                {               
                <a asp-area="" asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Id"
               class="btn btn-warning">Edit</a>
                <a asp-area="" asp-controller="Product" asp-action="Delete" asp-route-id="@Model.Id"
               class="btn btn-danger">Delete</a>
                }
                <form class="input-group-sm" asp-area=""asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Model.Id">
                    <input type="submit" value="Buy" class="fs-6 btn btn-success mb-3 p-2" />
                </form>
                <p></p>
            }
        </div>
    </div>
</div>

RockShop/Views/Shared/_UserMessages.cshtml
@using RockShop.Core.Constants

@if(TempData[MessageConstants.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstants.ErrorMessage].ToString()');})
    </script>
}

@if (TempData[MessageConstants.WarningMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstants.WarningMessage].ToString()'); })
    </script>
}

@if (TempData[MessageConstants.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstants.SuccessMessage].ToString()'); })
    </script>
}