RockShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using RockShop.Core.Contracts;
using System.Security.Claims;

namespace RockShop.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService cartService;

        public CartController(ICartService _cartService)
        {
            cartService = _cartService;
        }

        public async Task<IActionResult> AddToCart(int id)
        {
            try
            {
                var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

                await cartService.AddToCart(id, accId);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("All", "Product");
        }

        public async Task<IActionResult> GetCart()
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

            var model = await cartService.GetCart(accId);

            return View("ShoppingCart", model);
        }

        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

            await cartService.RemoveFromCart(id, accId);

            return RedirectToAction(nameof(GetCart));
        }
    }
}

RockShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RockShop.Core.Contracts;
using RockShop.Core.Models.Order;
using System.Security.Claims;

namespace RockShop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IProductService productService;
        private readonly IStaffService staffService;
        private readonly IOrderService orderService;

        public OrderController(IProductService _productService
                              ,IStaffService _staffService
                              ,IOrderService _orderService)
        {
            productService = _productService;
            staffService = _staffService;
            orderService = _orderService;
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            var model = new OrderViewModel();

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel model)
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await orderService.Checkout(accId, model);
            

            return RedirectToAction("All", "Product");
        }
    }
}

RockShop/Views/Cart/ShoppingCart.cshtml
@model IEnumerable<ProductServiceModel>

@{
    ViewBag.Title = "Your Shopping cart";
    decimal sum = 0;
}

<h2 class ="text-center">@ViewBag.Title</h2>
<hr/>

@foreach (var product in Model)
    {
        <div class="card col-4" style="width: 20rem; ">
            <img class="card-img-top" style="width: 18rem;"
             src="@product.ImageUrl" alt="Product Image">
            <div class="card-body">
                <h5 class="card-title mt-1">@product.Name</h5>
            </div>
            <h6>
                Price:
                <b>@String.Format("{0:f2}", product.Price) BGN</b>
            </h6>
            <form class="input-group-sm" asp-controller="Cart" asp-action="RemoveFromCart" asp-route-id="@product.Id">
                <input class="fs-6 btn btn-success mb-3 p-2" type="submit" value="Remove from Cart" />
            </form>
        </div>
        sum += product.Price;
    }
<div style="position: absolute; bottom: 150px; right: 300px;">
    <h6>
        Total:
        <b>@String.Format("{0:f2}", sum) BGN</b>
    </h6>
    <a class="btn-outline-success" asp-area="" asp-controller="Order" asp-action="Checkout">Checkout</a>
 </div>
        