RockShop/Areas/Admin/Controllers/AdminOrderController.cs
using Microsoft.AspNetCore.Mvc;
using RockShop.Core.Contracts;
using RockShop.Core.Models.Order;
using RockShop.Core.Models.Product;
using static RockShop.Areas.Admin.Constants.AdminConstants;

namespace RockShop.Areas.Admin.Controllers
{
    public class AdminOrderController : BaseController
    {
        private readonly IProductService productService;
        private readonly IStaffService staffService;
        private readonly IOrderService orderService;

        public AdminOrderController(IProductService _productService
                              , IStaffService _staffService
                              , IOrderService _orderService)
        {
            productService = _productService;
            staffService = _staffService;
            orderService = _orderService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await orderService.All();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> All(IEnumerable<OrderServiceModel> model)
        {
            return RedirectToAction("All", "AdminOrders");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await orderService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }
            if (!User.IsInRole(AdminRoleName))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var model = await orderService.OrderDetailsById(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, OrderViewModel model)
        {
            if ((await orderService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }
            if (!User.IsInRole(AdminRoleName))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            await orderService.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

RockShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using RockShop.Core.Contracts;
using System.Security.Claims;

namespace RockShop.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService cartService;

        public CartController(ICartService _cartService)
        {
            cartService = _cartService;
        }

        public async Task<IActionResult> AddToCart(int id)
        {
            try
            {
                var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

                await cartService.AddToCart(id, accId);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("All", "Product");
        }

        public async Task<IActionResult> GetCart()
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

            var model = await cartService.GetCart(accId);

            return View("ShoppingCart", model);
        }

        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var accId = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.NameIdentifier)?.Value;

            await cartService.RemoveFromCart(id, accId);

            return RedirectToAction(nameof(GetCart));
        }
    }
}

RockShop/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rock Shop - Administrator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RockShop.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <partial name="_UserMessages" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rock Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">Catalog</a>
                        </li>
                        @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="GetCart">Shopping Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Add">Add a product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminOrder" asp-action="All">Orders</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1>Administration Area</h1>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - RockShop
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RockShop/Areas/Admin/Views/Shared/_OrderPartial.cshtml
@model OrderServiceModel

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>First name:@Model.FirstName</h4>
            <h4>Second name:@Model.SecondName</h4>
            <h4>Adress:@Model.Address</h4>
            <h4>Phone number:@Model.PhoneNumber</h4>
                @foreach (var product in Model.OrderProducts)
            {
                <partial name="_OrderProductPartial" model="@product"/>
            }
            <br />
            @if (this.User.Identity.IsAuthenticated)
            {
                if (this.User.IsInRole(AdminRoleName))
                {
                    <a asp-area="Admin" asp-controller="AdminOrder" asp-action="Delete" asp-route-id="@Model.Id"
               class="btn btn-success">Finish</a>
                }
                <p></p>
            }
        </div>
    </div>
</div>

RockShop/Areas/Admin/Views/Shared/_OrderProductPartial.cshtml
@model OrderProductServiceModel

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>Product: @Model.ProductId</h4>
            <br />
        </div>
    </div>
</div>